# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSNative

#pod 'JKEventHandler'

pod 'JKWKWebViewHandler'
end
